# Copyright (C) 2026 fierman
# SPDX-License-Identifier: GPL-3.0-only
"""Low-level access to Tank Battle Classic scene files (Unity 6, IL2CPP).

Reading goes through UnityPy. The field layouts of the game's scripts
(MonoBehaviours) come from layouts/tbc_layouts.json.gz, generated by
packaging/generate_layouts.py from GameAssembly.dll + global-metadata.dat with
TypeTreeGeneratorAPI (AssetStudio backend, corrected for the missing alignment
flag on m_Enabled). The file records a fingerprint of the game's script
metadata. When the installed game differs (after a game update), every script
object is checked on reading: it must use exactly its stored size, otherwise
LayoutMismatch is raised instead of misreading or corrupting it. When
TypeTreeGeneratorAPI is installed (development), layouts are generated live
for a game that differs from the file.

Writing does not use UnityPy's file writer, because that rewrites the whole
data area with a different object alignment. Instead the original object data
is kept verbatim: changed and new objects are appended to the data area
(16-byte aligned) and the metadata block (types, object table, script
references, external files) is regenerated; for an unchanged file it is
byte-identical to the original.
"""

import copy
import gzip
import hashlib
import io
import json
import os
import struct
import sys

import UnityPy
from UnityPy.files import SerializedFile as _UnitySerializedFile
from UnityPy.streams import EndianBinaryReader
from fsspec.implementations.local import LocalFileSystem
from UnityPy.helpers.TypeTreeNode import TypeTreeNode
from UnityPy.streams import EndianBinaryWriter
UNITY_VERSION = "6000.2.10f1"  # fallback when the game files do not state it
HEADER_SIZE = 48
DATA_ALIGN = 16
LAYOUTS_FILE = os.path.join("layouts", "tbc_layouts.json.gz")


class LayoutMismatch(ValueError):
    """A script object does not match the editor's stored layout (the game was
    updated after this editor version was made)."""


def layouts_path():
    base = getattr(sys, "_MEIPASS", None) or os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base, LAYOUTS_FILE)


def script_key(asm, ns, cls):
    return f"{asm}|{ns}.{cls}" if ns else f"{asm}|{cls}"


def fixed_layout(base_nodes):
    """[(level, type, name, meta flag)] from generated nodes, with the alignment
    flag that the generator omits on m_Enabled."""
    out = []
    for b in base_nodes:
        flag = b.m_MetaFlag
        if b.m_Level == 1 and b.m_Name == "m_Enabled":
            flag |= 0x4000
        out.append((b.m_Level, b.m_Type, b.m_Name, flag))
    return out


def layout_tree(rows):
    return TypeTreeNode.from_list([TypeTreeNode(lv, t, n, 0, 0, m_MetaFlag=f) for lv, t, n, f in rows])


class _ReadAllFileSystem(LocalFileSystem):
    """Local file system that reads files fully and closes them at once, so
    UnityPy never keeps game files open (open files block saving on Windows)."""

    def open(self, path, mode="rb", **kwargs):
        if "r" in mode and "+" not in mode:
            with open(self._strip_protocol(path), "rb") as f:
                return io.BytesIO(f.read())
        return super().open(path, mode, **kwargs)


def find_game_root(path):
    """Return the game root (folder holding GameAssembly.dll) for a game or data path."""
    path = os.path.abspath(path)
    for cand in (path, os.path.dirname(path)):
        if os.path.isfile(os.path.join(cand, "GameAssembly.dll")):
            return cand
    raise FileNotFoundError(f"GameAssembly.dll not found at or above {path}")


class GameContext:
    """Shared, per-game data: data folder, script table and layout generator."""

    def __init__(self, game_root):
        self.root = find_game_root(game_root)
        data = [d for d in os.listdir(self.root) if d.endswith("_Data")]
        if not data:
            raise FileNotFoundError(f"No *_Data folder in {self.root}")
        self.data_dir = os.path.join(self.root, data[0])
        meta = os.path.join(self.data_dir, "il2cpp_data", "Metadata", "global-metadata.dat")
        with open(meta, "rb") as f:
            self.metadata_sha256 = hashlib.sha256(f.read()).hexdigest()
        self.unity_version = self._read_unity_version()
        self.layouts, self.layout_info = {}, {}
        try:
            with gzip.open(layouts_path(), "rt", encoding="utf-8") as f:
                data = json.load(f)
            self.layouts, self.layout_info = data["layouts"], data["info"]
        except OSError:
            pass
        self.layouts_exact = self.layout_info.get("metadata_sha256") == self.metadata_sha256
        self.generator = None
        if not self.layouts_exact:
            self.generator = self.live_generator()
        self._node_cache = {}
        self._external_cache = {}

        with open(os.path.join(self.data_dir, "globalgamemanagers.assets"), "rb") as f:
            genv = UnityPy.load(f.read())
        gsf = next(iter(genv.files.values()))
        self.scripts = {}
        for o in gsf.objects.values():
            if o.type.name == "MonoScript":
                s = o.read()
                self.scripts[o.path_id] = (s.m_AssemblyName, s.m_Namespace, s.m_ClassName)

        self.reload_build_settings()

    def live_generator(self):
        """TypeTreeGeneratorAPI on this game, when installed (development only)."""
        try:
            from TypeTreeGeneratorAPI import TypeTreeGenerator
        except ImportError:
            return None
        with open(os.path.join(self.root, "GameAssembly.dll"), "rb") as f:
            ga = f.read()
        with open(os.path.join(self.data_dir, "il2cpp_data", "Metadata", "global-metadata.dat"), "rb") as f:
            gm = f.read()
        gen = TypeTreeGenerator(self.unity_version, "AssetStudio")
        gen.load_il2cpp(ga, gm)
        return gen

    @property
    def verify_layouts(self):
        """True when stored layouts are used for a game they were not made for."""
        return not self.layouts_exact and self.generator is None

    def layout_status(self):
        if self.layouts_exact:
            return "script layouts match this game version"
        if self.generator is not None:
            return "script layouts generated from this game (development)"
        return ("this game version is newer than the editor's script layouts; objects whose "
                "scripts changed cannot be edited until the editor is updated")

    def _read_unity_version(self):
        """Unity version the game was built with (from globalgamemanagers), so a
        game rebuilt with a newer Unity keeps working."""
        try:
            with open(os.path.join(self.data_dir, "globalgamemanagers"), "rb") as f:
                sf = next(iter(UnityPy.load(f.read()).files.values()))
            v = str(sf.unity_version)
            return v if v and v[0].isdigit() else UNITY_VERSION
        except Exception:
            return UNITY_VERSION

    def reload_build_settings(self):
        """Re-read the scene list (BuildSettings) from globalgamemanagers."""
        self.scene_names = []
        with open(os.path.join(self.data_dir, "globalgamemanagers"), "rb") as f:
            benv = UnityPy.load(f.read())
        for o in benv.objects:
            if o.type.name == "BuildSettings":
                self.scene_names = list(o.read_typetree()["scenes"])
                break

    def asset_files(self):
        """Shared asset files of the game (sharedassetsN.assets, resources.assets)."""
        out = []
        for f in os.listdir(self.data_dir):
            if (f.startswith("sharedassets") and f.endswith(".assets")) or f == "resources.assets":
                out.append(f)
        return sorted(out, key=lambda f: (len(f), f))

    def files_using_script(self, class_name):
        """Asset files whose objects use the given game script, found from the
        file metadata only (fast: no object data is read)."""
        cache = self.__dict__.setdefault("_script_files", {})
        if class_name in cache:
            return cache[class_name]
        pids = {p for p, info in self.scripts.items() if info[2] == class_name}
        hits = []
        for f in self.asset_files():
            try:
                with open(os.path.join(self.data_dir, f), "rb") as fh:
                    meta_size = struct.unpack_from(">I", fh.read(HEADER_SIZE), 20)[0]
                    fh.seek(0)
                    buf = fh.read(HEADER_SIZE + meta_size)
                sf = _UnitySerializedFile(EndianBinaryReader(buf), name=f)
            except Exception:
                continue
            ext = [e.path for e in sf.externals]
            for st in sf.script_types:
                fid = st.local_serialized_file_index
                if fid > 0 and ext[fid - 1] == "globalgamemanagers.assets" and st.local_identifier_in_file in pids:
                    hits.append(f)
                    break
        cache[class_name] = hits
        return hits

    def scene_path(self, index):
        return os.path.join(self.data_dir, f"level{index}")

    def scene_label(self, index):
        if index < len(self.scene_names):
            return os.path.splitext(os.path.basename(self.scene_names[index]))[0]
        return f"level{index}"

    def script_nodes(self, script_pid):
        """Corrected type tree for the MonoScript with this path id, or None."""
        if script_pid in self._node_cache:
            return self._node_cache[script_pid]
        node = None
        info = self.scripts.get(script_pid)
        if info:
            rows = None
            if self.generator is not None:
                asm, ns, cls = info
                try:
                    base = self.generator.get_nodes(asm + ".dll", f"{ns}.{cls}" if ns else cls)
                    rows = fixed_layout(base) if base else None
                except Exception:
                    rows = None
            else:
                rows = self.layouts.get(script_key(*info))
            if rows:
                node = layout_tree(rows)
        self._node_cache[script_pid] = node
        return node

    def external(self, name):
        """Open (cached) another serialized file of the game by its external path."""
        if name not in self._external_cache:
            rel = name
            if rel.startswith("Library/"):
                rel = "Resources/" + rel[len("Library/"):]
            path = os.path.join(self.data_dir, rel)
            sf = None
            if os.path.isfile(path):
                with open(path, "rb") as f:
                    raw = f.read()
                env = UnityPy.Environment(fs=_ReadAllFileSystem(), path=os.path.dirname(path))
                sf = env.load_file(raw, name=os.path.basename(path))
            self._external_cache[name] = sf
        return self._external_cache[name]


class SceneFile:
    """One levelN file: typed read access, edits, and minimal patch-saving."""

    def __init__(self, ctx, path):
        self.ctx = ctx
        self.path = path
        with open(path, "rb") as f:
            self.raw = f.read()
        env = UnityPy.load(self.raw)
        self.sf = next(iter(env.files.values()))
        self.endian = self.sf.header.endian
        self.externals = [e.path for e in self.sf.externals]
        self.objects = self.sf.objects
        self._cache = {}
        self.changed = {}
        self.new_objects = {}
        self.foreign = {}
        self.meta_changed = False
        version = struct.unpack_from(">I", self.raw, 8)[0]
        if version < 22:
            raise ValueError(f"Unsupported serialized file version {version}")
        self.metadata_size, self.file_size, self.data_offset = struct.unpack_from(">IQQ", self.raw, 20)

    # ---- reading -------------------------------------------------------

    def _template(self, pid):
        """Existing object whose type (and layout) a new object shares, or None."""
        if pid in self.new_objects:
            return self.new_objects[pid][0]
        return pid

    def type_name(self, pid):
        if pid in self.foreign:
            return self.foreign[pid][1]
        return self.objects[self._template(pid)].type.name

    def type_id(self, pid):
        if pid in self.foreign:
            return self.foreign[pid][0]
        return self.objects[self._template(pid)].type_id

    def all_pids(self):
        return list(self.objects.keys()) + list(self.new_objects.keys())

    def script_class(self, pid):
        """Class name of a MonoBehaviour's script (game scripts only), else None."""
        d = self.read(pid, head_only=True)
        p = d["m_Script"]
        if p["m_FileID"] == 0:
            return None
        if self.externals[p["m_FileID"] - 1] != "globalgamemanagers.assets":
            return None
        info = self.ctx.scripts.get(p["m_PathID"])
        return info[2] if info else None

    def _nodes(self, pid, head_only=False):
        if pid in self.foreign:
            return self.foreign[pid][2]
        obj = self.objects[self._template(pid)]
        if obj.type.name != "MonoBehaviour":
            return None
        if head_only:
            return "head"
        head = obj.parse_monobehaviour_head()
        p = head.m_Script
        if p.m_FileID == 0 or self.externals[p.m_FileID - 1] != "globalgamemanagers.assets":
            raise ValueError(f"No layout for MonoBehaviour {pid}")
        nodes = self.ctx.script_nodes(p.m_PathID)
        if nodes is None:
            raise ValueError(f"No layout for MonoBehaviour {pid}")
        return nodes

    def nodes_for(self, pid):
        """Type tree used to (de)serialize an object."""
        n = self._nodes(pid)
        if n is None:
            n = self.objects[self._template(pid)]._get_typetree_node()
        return n

    def read(self, pid, head_only=False):
        """Return the object's fields as a dict. Edits must go through write()."""
        if pid in self._cache:
            return self._cache[pid]
        if pid in self.new_objects:
            raise KeyError(f"New object {pid} has no cached data")
        obj = self.objects[pid]
        if obj.type.name == "MonoBehaviour" and head_only:
            head = obj.parse_monobehaviour_head()
            return {"m_GameObject": {"m_FileID": head.m_GameObject.m_FileID,
                                     "m_PathID": head.m_GameObject.m_PathID},
                    "m_Script": {"m_FileID": head.m_Script.m_FileID,
                                 "m_PathID": head.m_Script.m_PathID}}
        nodes = self._nodes(pid)
        if nodes is None:
            d = obj.read_typetree(nodes=nodes, wrap=False, check_read=False)
        else:
            try:
                d = obj.read_typetree(nodes=nodes, wrap=False, check_read=True)
            except Exception as e:
                name = nodes.m_Type if hasattr(nodes, "m_Type") else "script"
                raise LayoutMismatch(f"{name} does not match the editor's layout for this game version "
                                     f"({e}); update the editor") from None
        self._cache[pid] = d
        return d

    # ---- editing -------------------------------------------------------

    def write(self, pid, data):
        """Store new field values for an object (existing or new)."""
        self._cache[pid] = data
        if pid in self.new_objects:
            self.new_objects[pid] = (self.new_objects[pid][0], True)
        else:
            self.changed[pid] = True

    def next_pid(self):
        return max(self.all_pids()) + 1

    def add_object(self, template_pid, data):
        """Create a new object of the same type as template_pid with these fields."""
        src = self._template(template_pid)
        pid = self.next_pid()
        self.new_objects[pid] = (src, True)
        if template_pid in self.foreign:
            self.foreign[pid] = self.foreign[template_pid]
        self._cache[pid] = data
        return pid

    def add_foreign(self, type_id, type_name, nodes, data):
        """Create a new object with an explicit type entry and layout (objects
        imported from another scene)."""
        pid = self.next_pid()
        self.new_objects[pid] = (None, True)
        self.foreign[pid] = (type_id, type_name, nodes)
        self._cache[pid] = data
        return pid

    def remove_new(self, pid):
        self.new_objects.pop(pid, None)
        self.foreign.pop(pid, None)
        self._cache.pop(pid, None)

    # ---- metadata: externals and types ----------------------------------

    def ensure_external(self, identifier):
        """fileID (1-based) of an external file, adding the FileIdentifier when missing."""
        if identifier.path in self.externals:
            return self.externals.index(identifier.path) + 1
        self.sf.externals.append(copy.copy(identifier))
        self.externals.append(identifier.path)
        self.meta_changed = True
        return len(self.externals)

    def ensure_external_path(self, path):
        """fileID of a game file by name, adding a reference when missing (build
        references carry no GUID, so one can be made from any existing entry)."""
        if path in self.externals:
            return self.externals.index(path) + 1
        ident = copy.copy(self.sf.externals[0])
        ident.path = path
        return self.ensure_external(ident)

    def ensure_type(self, other, other_type_id):
        """Type index in this file for type other_type_id of SceneFile `other`,
        adding the SerializedType (and its script reference) when missing."""
        st = other.sf.types[other_type_id]
        for i, t in enumerate(self.sf.types):
            if t.class_id != st.class_id or t.old_type_hash != st.old_type_hash:
                continue
            if st.class_id == 114 and t.script_id != st.script_id:
                continue
            return i
        nt = copy.copy(st)
        if st.class_id == 114 and st.script_type_index >= 0:
            ref = other.sf.script_types[st.script_type_index]
            fid = ref.local_serialized_file_index
            if fid > 0:
                fid = self.ensure_external(other.sf.externals[fid - 1])
            idx = next((i for i, s in enumerate(self.sf.script_types)
                        if s.local_serialized_file_index == fid
                        and s.local_identifier_in_file == ref.local_identifier_in_file), None)
            if idx is None:
                nr = copy.copy(ref)
                nr.local_serialized_file_index = fid
                self.sf.script_types.append(nr)
                idx = len(self.sf.script_types) - 1
            nt.script_type_index = idx
        self.sf.types.append(nt)
        self.meta_changed = True
        return len(self.sf.types) - 1

    @property
    def dirty(self):
        return bool(self.changed or self.new_objects or self.meta_changed)

    def serialize(self, pid):
        writer = EndianBinaryWriter(endian=self.endian)
        if pid in self.foreign:
            obj = next(iter(self.objects.values()))
        else:
            obj = self.objects[self._template(pid)]
        obj.save_typetree(self._cache[pid], nodes=self.nodes_for(pid), writer=writer)
        return writer.bytes

    # ---- saving --------------------------------------------------------

    def _metadata(self, entries):
        """Serialize the metadata block; entries = [(pid, offset, size, type_id)].
        Reproduces the original bytes exactly for an unchanged file."""
        sf = self.sf
        h = sf.header
        w = EndianBinaryWriter(endian=h.endian)
        w.write_string_to_null(sf.unity_version)
        w.write_int(sf._m_target_platform)
        w.write_boolean(sf._enable_type_tree)
        w.write_int(len(sf.types))
        for t in sf.types:
            t.write(sf, w, False)
        w.write_int(len(entries))
        for pid, off, size, tid in entries:
            w.align_stream()
            w.write_long(pid)
            w.write_long(off)
            w.write_u_int(size)
            w.write_int(tid)
        w.write_int(len(sf.script_types))
        for st in sf.script_types:
            st.write(h, w)
        w.write_int(len(sf.externals))
        for e in sf.externals:
            e.write(h, w)
        w.write_int(len(sf.ref_types or []))
        for r in sf.ref_types or []:
            r.write(sf, w, True)
        w.write_string_to_null(sf.userInformation)
        return w.bytes

    def build(self):
        """Return the patched file bytes: original data kept verbatim, changed and
        new objects appended (16-byte aligned), metadata regenerated."""
        raw = self.raw
        data = bytearray(raw[self.data_offset:self.file_size])

        def append(blob):
            data.extend(b"\0" * ((-len(data)) % DATA_ALIGN))
            off = len(data)
            data.extend(blob)
            return off

        entries = {}
        for pid, o in self.objects.items():
            entries[pid] = (pid, o.byte_start - self.data_offset, o.byte_size, o.type_id)
        for pid in sorted(self.changed):
            blob = self.serialize(pid)
            entries[pid] = (pid, append(blob), len(blob), self.objects[pid].type_id)
        for pid in sorted(self.new_objects):
            blob = self.serialize(pid)
            entries[pid] = (pid, append(blob), len(blob), self.type_id(pid))

        meta = self._metadata([entries[p] for p in sorted(entries)])
        data_offset = HEADER_SIZE + len(meta)
        data_offset += (-data_offset) % DATA_ALIGN
        file_size = data_offset + len(data)
        header = bytearray(raw[:HEADER_SIZE])
        struct.pack_into(">IQQ", header, 20, len(meta), file_size, data_offset)
        return bytes(header + meta + b"\0" * (data_offset - HEADER_SIZE - len(meta)) + data)

    def save(self, path=None):
        path = path or self.path
        out = self.build()
        check = next(iter(UnityPy.load(out).files.values()))
        if len(check.objects) != len(self.objects) + len(self.new_objects):
            raise ValueError("internal check failed: object count mismatch after build")
        tmp = path + ".tmp"
        with open(tmp, "wb") as f:
            f.write(out)
        os.replace(tmp, path)
        return len(out)
